export type * from "./login";
export type * from "./axios";
export type * from "./forgot";
export type * from "./patientList";
export type * from "./templates";
export type * from "./radiologistlist";
export type * from "./patienthistory";
export type * from "./logout";
export type * from "./optionList";
