export const ENDPOINTS = {
  login: "/risGateway/user/login",
  generateOtp: "/risGateway/user/resetPCodeValidate",
  forgot: "/risGateway/user/createPassword",
  getPatientList: "/risGateway/api/getPatientVisitList",
  getRadioloistTemplate: "/risGateway/api/getRadiologistTemplates",
  getRadiologistList: "/risGateway/api/getRadiologistList",
  addUpdateTemplate: "/risGateway/api/addUpdateTemplate",
  getPatientHistory: "/risGateway/api/getPatientVisitHistory",
  logout: "/risGateway/user/logout",
  optionList: "/risGateway/api/getOptionList",
  getTechnicalNotes: "/risGateway/api/getPatientClinicalNotesList",
  addUpdateTechnicalNotes: "/risGateway/api/addUpdatePatientClinicalNotes",
  getAllergies: "/risGateway/api/getPatientAllergyList",
  addUpdateAllergy: "/risGateway/api/addUpdatePatientAllergy",
  uploadPatientDocument: "/risGateway/api/uploadPatientDocument",
  getUploadedDocument: "/risGateway/api/getPatientDocument",
};
